<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>software.xdev.vaadin.maps-leaflet</groupId>
		<artifactId>src</artifactId>
		<version>6.1.0</version>
	</parent>

	<artifactId>bom</artifactId>
	<packaging>pom</packaging>

	<name>LeafletMap for Vaadin - BOM</name>
	<description>LeafletMap for Vaadin - BOM</description>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>software.xdev.vaadin.maps-leaflet</groupId>
				<artifactId>flow</artifactId>
				<version>6.1.0</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.vaadin.maps-leaflet.plugins</groupId>
				<artifactId>geoman</artifactId>
				<version>6.1.0</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.vaadin.maps-leaflet.plugins</groupId>
				<artifactId>leaflet-markercluster</artifactId>
				<version>6.1.0</version>
			</dependency>
			<dependency>
				<groupId>software.xdev.vaadin.maps-leaflet.plugins</groupId>
				<artifactId>maplibre-gl-leaflet</artifactId>
				<version>6.1.0</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<profiles>
		<profile>
			<id>publish</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>flatten-maven-plugin</artifactId>
						<configuration>
							<flattenMode>bom</flattenMode>
							<pomElements>
								<!-- properties are not needed downstream -->
								<properties>remove</properties>
							</pomElements>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
