<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>software.xdev.vaadin.maps-leaflet</groupId>
		<artifactId>src</artifactId>
		<version>6.0.2-SNAPSHOT</version>
	</parent>

	<artifactId>plugins</artifactId>
	<packaging>pom</packaging>

	<modules>
		<module>geoman</module>
		<module>leaflet-markercluster</module>
        <module>maplibre-gl-leaflet</module>
	</modules>

    <dependencies>
		<dependency>
			<groupId>software.xdev.vaadin.maps-leaflet</groupId>
			<artifactId>flow</artifactId>
			<version>6.0.2-SNAPSHOT</version>
		</dependency>
	</dependencies>
</project>
