name: Test Deployment

on:
  workflow_dispatch:

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v7

    - name: Set up JDK
      uses: actions/setup-java@v6
      with: # running setup-java overwrites the settings.xml
        distribution: 'temurin'
        java-version: '17'
        server-id: github-central
        server-password-env-var: PACKAGES_CENTRAL_TOKEN
        gpg-passphrase-env-var: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Only import once

    - name: Publish to GitHub Packages Central
      run: ../mvnw -B deploy -P publish -DaltDeploymentRepository=github-central::https://maven.pkg.github.com/xdev-software/central
      working-directory: src
      env:
        PACKAGES_CENTRAL_TOKEN: ${{ secrets.PACKAGES_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Set up JDK
      uses: actions/setup-java@v6
      with: # running setup-java again overwrites the settings.xml
        distribution: 'temurin'
        java-version: '17'
        server-id: sonatype-central-portal
        server-username-env-var: MAVEN_CENTRAL_USERNAME
        server-password-env-var: MAVEN_CENTRAL_TOKEN
        gpg-passphrase-env-var: MAVEN_GPG_PASSPHRASE

    - name: Publish to Central Portal
      run: ../mvnw -B deploy -P publish,publish-sonatype-central-portal
      working-directory: src
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.SONATYPE_MAVEN_CENTRAL_PORTAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_MAVEN_CENTRAL_PORTAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
